FROM alpine

RUN mkdir /app
RUN mkdir /app/bin
RUN cd /app/bin

COPY cxonerepositoryset /app/bin/cxonerepositoryset
COPY config.yaml /app/bin/config.yaml
COPY LICENSE /app/bin/LICENSE

RUN chmod -R 777 /app/bin

ENTRYPOINT ["/app/bin/cxonerepositoryset"]